### ISSUE TITLE
[Error report not reproducible] filters support a maximum of 30 elements in the value [Iterable].

### ISSUE THREAD

**Issue by gohil-rahul-tft** [kosukesaigusa/geoflutterfire_plus#100]
I am not using any firestore query along with the fetchWithin function still getting below error.

> 'package:cloud_firestore/src/query.dart': Failed assertion: line 741 pos 11: '(operator != 'in' && operator != 'array-contains-any') ||
> I/flutter (15285):               (value as Iterable).length <= 30': 'in' filters support a maximum of 30 elements in the value [Iterable].

My code:- 

```dart
Future<void> findNearbyLocations() async {
    Future.delayed(Duration.zero);

    try {
      // Query for "Akota Garden" location
      QuerySnapshot querySnapshot = await fireStore
          .collection('locations')
          .where('place_name', isEqualTo: 'Akota Garden')
          .get();

      // Get the first document from the query result
      DocumentSnapshot documentSnapshot = querySnapshot.docs.first;

      // Get the coordinates of "Akota Garden"
      GeoPoint akotaGardenLocation = documentSnapshot['coordinates'];

      // Create a GeoFirePoint for "Akota Garden"
      GeoFirePoint center = GeoFirePoint(akotaGardenLocation);

      // Reference to locations collection.
      final CollectionReference<Map<String, dynamic>> locationCollectionRef =
          fireStore.collection('locations');

      final result =
          await GeoCollectionReference(locationCollectionRef).fetchWithin(
        center: center,
        radiusInKm: 6,
        field: 'geo',
        strictMode: true,
        geopointFrom: geopointFrom,
      );

      for (var value in result) {
        String placeName = value['place_name'];
        final distance =
            center.distanceBetweenInKm(geopoint: value['coordinates']);

        print(placeName);
        print("Distance : $distance");
      }
    } catch (e) {
      print("ERROR IN LOCATION : $e");
    }
  }
  ```

**Comment by kosukesaigusa** [comment]
Thank you for creating an issue @gohil-rahul-tft!

I checked your code above, and the part you are using geoflutterfire_plus geo query is here:

```dart
final result =
          await GeoCollectionReference(locationCollectionRef).fetchWithin(
  center: center,
  radiusInKm: 6,
  field: 'geo',
  strictMode: true,
  geopointFrom: geopointFrom,
);
```

and seems nothing is wrong.

I also tried to reproduce the error you report

> I/flutter (15285): (value as Iterable).length <= 30': 'in' filters support a maximum of 30 elements in the value [Iterable].

with the following code:

```dart
class GeoflutterfirePlusSample extends StatelessWidget {
  const GeoflutterfirePlusSample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: [
          ListTile(
            leading: const Icon(Icons.map),
            title: const Text('Call fetchWithin method'),
            onTap: () async {
              final locationCollectionRef =
                  FirebaseFirestore.instance.collection('locations');
              const center = GeoFirePoint(GeoPoint(35.681236, 139.767125));
              final result = await GeoCollectionReference(locationCollectionRef)
                  .fetchWithin(
                center: center,
                radiusInKm: 6,
                field: 'geo',
                strictMode: true,
                geopointFrom: (data) => (data['geo']
                    as Map<String, dynamic>)['geopoint'] as GeoPoint,
              );
              print(result);
            },
          ),
        ],
      ),
    );
  }
}
```

but it just returns normal result `List<DocumentSnapshot<Map<String, dynamic>>>` without errors.

If you get a minimal reproducible code (your code above still seems to include some geofluttefire_plus unrelated codes) of the problem, please reply here and share it!

**Comment by gohil-rahul-tft** [comment]
The problem occurs when we have multiple locations or results nearby within a 6 KM radius. In my case, I was having 30+ results and that's why this problem occurred.

**Comment by kosukesaigusa** [comment]
@gohil-rahul-tft Thank you for your reply!

For example, I added 50 near locations from the center point like the following `FloatingActionButton.onPressed`, and called `fetchWithin`, successfully 50 results are returned.

```dart
/// geoflutterfire_plus パッケージの動作確認用 Widget.
class GeoflutterfirePlusSample extends StatelessWidget {
  const GeoflutterfirePlusSample({super.key});

  static const _latitude = 35.681236;

  static const _longitude = 139.767125;

  static final _locationsCollectionReference =
      FirebaseFirestore.instance.collection('sampleLocations');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: [
          ListTile(
            leading: const Icon(Icons.map),
            title: const Text('Call fetchWithin method'),
            onTap: () async {
              const center = GeoFirePoint(GeoPoint(_latitude, _longitude));
              final result =
                  await GeoCollectionReference(_locationsCollectionReference)
                      .fetchWithin(
                center: center,
                radiusInKm: 6,
                field: 'geo',
                strictMode: true,
                geopointFrom: (data) => (data['geo']
                    as Map<String, dynamic>)['geopoint'] as GeoPoint,
              );
              // output: 50
              debugPrint(result.length.toString());
            },
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          for (var i = 0; i < 50; i++) {
            final newLatitude = _latitude + i * 0.0001;
            final newLongitude = _longitude + i * 0.0001;
            final newGeoFirePoint =
                GeoFirePoint(GeoPoint(newLatitude, newLongitude));
            _locationsCollectionReference.add(<String, dynamic>{
              'geo': <String, dynamic>{
                'geopoint': newGeoFirePoint.geopoint,
                'geohash': newGeoFirePoint.geohash,
              },
            });
          }
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

I think there are no `in` or `array-contains` query in geoflutterfire_plus package, so the error might occur from your own code not from geoflutterfire_plus?

I would like you to check your own code, or share the minimal reproducible example code please!

**Comment by gohil-rahul-tft** [comment]
@kosukesaigusa Apologies from my side, you are right, I tested my code again and found that issue is in my code.  

Firestore has limitation on whereIn upto 30 records.

`final List<Stores> nearbyStores = await getNearbyStores(
        radius: radius,
        firestore: fireStore,
        userLocation: GeoPoint(20.68016662, -103.3822084),
      );

      try {

        // Fetch the products in a batched read
        final List<DocumentReference> storeRefs = nearbyStores
            .map((store) => fireStore
                .collection(StoreConstant.storeCollection)
                .doc(store.id))
            .toList();

        // Fetch all store products that meet the conditions
        final QuerySnapshot storeProductsSnapshot = await fireStore
            .collection('products_mvp')
            .where('is_exist', isEqualTo: true)
            .where('storeRef', whereIn: storeRefs)
            .get();

 catch (e) {
        print("STORE ERROR = $e");
      }`
      
 And thank you for the quick response. :)
