### ISSUE TITLE
One time query as Future

### ISSUE THREAD

**Issue by JoergPf** [kosukesaigusa/geoflutterfire_plus#169]
Hi,
I saw a post that you can use fetchWithin method to fetch geo locations as Future. 
When my app starts I would like to query initially Firestore for objects in a certain distance. But only once and not as a stream. Is there an example?
Thanks

**Comment by kosukesaigusa** [comment]
@JoergPf 

Yes! You can call `GeoCollectionReference` class `fetchWithin` method defined in the following codes!

https://github.com/kosukesaigusa/geoflutterfire_plus/blob/685a2c857423654d2b441baec7e322c1463a8652/lib/src/geo_collection_reference.dart#L171

**Comment by JoergPf** [comment]
Great, thanks!
