### ISSUE TITLE
QueryBuilder not returning any results

### ISSUE THREAD

**Issue by stefandric** [kosukesaigusa/geoflutterfire_plus#188]
**geoflutterfire_plus: ^0.0.21**

When trying to inject additional query, I am not getting any results. When removing queryBuilder, I am getting all results.

Code:

```
var res =
      await GeoCollectionReference<Map<String, dynamic>>(collectionReference)
          .subscribeWithin(
            center: center,
            radiusInKm: radiusInKm,
            field: field,
            geopointFrom: geopointFrom,
            queryBuilder: (query) => query.where('archived', isEqualTo: false),
          )
          .first;

  final obj =
      res.map((docSnapshot) => Post.fromDocumentSnapshot(docSnapshot)).toList();

  return obj;
```

nor with fetchWithin

```
var res =
      await GeoCollectionReference<Map<String, dynamic>>(collectionReference)
          .fetchWithin(
    center: center,
    radiusInKm: radiusInKm,
    field: field,
    geopointFrom: geopointFrom,
    queryBuilder: (query) => query.where('archived', isEqualTo: false),
  );
```

i've tested it further because i thought it is something with my query, but passing null to query doesn't also work(I saw an example proj where null should get all values as well).

```
var res =
      await GeoCollectionReference<Map<String, dynamic>>(collectionReference)
          .fetchWithin(
    center: center,
    radiusInKm: radiusInKm,
    field: field,
    geopointFrom: geopointFrom,
    queryBuilder: (query) => null,
  );
```

**Comment by stefandric** [comment]
@kosukesaigusa any update on this?

**Comment by kosukesaigusa** [comment]
@stefandric 

Thank you for your comment and, sorry for my late reply!

May I ask you you have set necessary index on Cloud Firestore to execute the query?

https://github.com/kosukesaigusa/geoflutterfire_plus?tab=readme-ov-file#custom-query-conditions

![000038@2x](https://github.com/kosukesaigusa/geoflutterfire_plus/assets/13669049/d46215d7-7a75-4bde-931c-5c4f7c6cd659)
