### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by SinapseVB** [kosukesaigusa/geoflutterfire_plus#197]
I need to update the components of my application but the error below is occurring. Do you have any predictions on when it will be compatible?

Resolving dependencies...
Because geoflutterfire_plus >=0.0.21 depends on cloud_firestore ^4.17.0 and dochealth_core depends on cloud_firestore ^5.0.1, geoflutterfire_plus >=0.0.21 is forbidden.
So, because dochealth_core depends on geoflutterfire_plus ^0.0.21, version solving failed.

**Comment by eridiumeng** [comment]
I'm having this issue too, for now just added a dependency_override to I could update other packages

dependency_overrides:
  cloud_firestore: ^5.0.1

**Comment by kosukesaigusa** [comment]
@SinapseVB @eridiumeng 

Thank you for your comments! I created a PR to update dependencies and confirm both iOS and Android example app is successfully build:

https://github.com/kosukesaigusa/geoflutterfire_plus/pull/200

I will release new version with this change soon!

**Comment by kosukesaigusa** [comment]
v0.0.22 is released now!

@SinapseVB @eridiumeng

Please try to upgrade your app's dependencies! Sorry for the inconvenience!
