### ISSUE TITLE
Add cache first feature

### ISSUE THREAD

**Issue by Kurczaak** [kosukesaigusa/geoflutterfire_plus#199]
Frequent location changes resulted in a lot of calls to the Firestore. In order to prevent this I've opened a PR with an option `isCacheFirst` in order not to fetch already fetched data.

Check out the PR:
[https://github.com/kosukesaigusa/geoflutterfire_plus/pull/198](url)

**Comment by kosukesaigusa** [comment]
The new geoflutterfire_plus version v0.0.23, includes your contribution has been released!

https://pub.dev/packages/geoflutterfire_plus/changelog

![000098@2x](https://github.com/kosukesaigusa/geoflutterfire_plus/assets/13669049/9c9d4365-b5f6-40ef-baaa-66cf9a6a1e55)
