### ISSUE TITLE
'isCacheFirst' not working

### ISSUE THREAD

**Issue by Kurczaak** [kosukesaigusa/geoflutterfire_plus#204]
Hi, 
in my previous PR I've implemented the `isCacheFirst` functionality, however it's not working as expected. I haven't tested the implementation well enough. This time I did some tests with debugging and it seems to work correct. Let me know what you think, here's my PR:
https://github.com/kosukesaigusa/geoflutterfire_plus/pull/203

PS.
Sorry for the inconvenience, I promise to test my code better next time

**Comment by kosukesaigusa** [comment]
@Kurczaak 

Thank you for creating a PR again!

Now it's released in pub.dev!

https://pub.dev/packages/geoflutterfire_plus/changelog
