### ISSUE TITLE
Please update to rxdart ^0.28.0!!!

### ISSUE THREAD

**Issue by itismejy** [kosukesaigusa/geoflutterfire_plus#206]
Because no versions of geoflutterfire_plus match >0.0.24 <0.1.0 and geoflutterfire_plus 0.0.24 depends on rxdart ^0.27.1, geoflutterfire_plus ^0.0.24 requires rxdart ^0.27.1.
And because flutter_google_places_hoc081098 >=2.0.0 depends on rxdart ^0.28.0, geoflutterfire_plus ^0.0.24 is incompatible with flutter_google_places_hoc081098 >=2.0.0.
So, because gather depends on both flutter_google_places_hoc081098 ^2.0.0 and geoflutterfire_plus ^0.0.24, version solving failed.
exit code 1

**Comment by kosukesaigusa** [comment]
@itismejy 

It is because geoflutterfire_plus package depends on [fake_cloud_firestore](https://pub.dev/packages/fake_cloud_firestore) package and its comability.

It is only for test purpose, so let me think about we should remove the dependency.

**Comment by kosukesaigusa** [comment]
This PR removes [fake_cloud_firestore](https://pub.dev/packages/fake_cloud_firestore) package dependency and update rxdart to `^0.28.0`.

https://github.com/kosukesaigusa/geoflutterfire_plus/pull/208/files

Will be merged soon!

**Comment by kosukesaigusa** [comment]
Now it's released:

https://pub.dev/packages/geoflutterfire_plus/changelog

**Comment by itismejy** [comment]
thank you kousuke!
