### ISSUE TITLE
not getting import the package

### ISSUE THREAD

**Issue by sabahsayedk2000** [kosukesaigusa/geoflutterfire_plus#252]
installed GeoFlutterFire _plus package but cannot see the package to import  GeoCollectionReference<Map<String, dynamic>>(collectionReference)
        .subscribeWithin(
      center: center,
      radiusInKm: radiusInKm,
      field: field,
      geopointFrom: geopointFrom,
    );The method 'GeoCollectionReference' isn't defined for the type 'GymListRepository'.

**Comment by kosukesaigusa** [comment]
I think it is because some configuration on your project is wrong. 

Could you share both of the following?

- Your pubspec.yaml
- The result of `flutter doctor -v`
