### ISSUE TITLE
I don't get nearby location document already store same geopoint in firebase 

### ISSUE THREAD

**Issue by sabahsayedk2000** [kosukesaigusa/geoflutterfire_plus#253]
void gethotelGyms() async {
    // Your current location (center of the search)
    GeoPoint userLocation = GeoPoint(10.977850483946714,76.22587937861681);
//this geopoint already stored in firebase as geopoint varible

    // Search radius in kilometers
    double radiusInKm = 100;

    // Firestore collection reference
    final collectionReference = FirebaseFirestore.instance.collection('hotels');

    // Initialize GeoFirePoint for the user's location
    final geoCenter = GeoFirePoint(userLocation);

    // Initialize GeoCollectionReference for the Firestore collection
    final geoCollection = GeoCollectionReference<Map<String, dynamic>>(
      collectionReference,
    );

    // Fetch documents within the specified radius
    final stream = geoCollection.subscribeWithin(
      center: geoCenter,
      radiusInKm: radiusInKm,
      field: 'maplocation', // Ensure this matches your Firestore field name
      geopointFrom: (data) {
        // Extract the GeoPoint from Firestore document
        return data['maplocation'] as GeoPoint;
      },
    );

    // Listen to the stream and print nearby gym documents
    stream.listen((List<DocumentSnapshot<Map<String, dynamic>>> documents) {
      if (documents.isEmpty) {
        print("No hotel found within the specified radius.");
      } else {
        for (var doc in documents) {
          print("hotel Document: ${doc.data()}");
        }
      }
    }, onError: (error) {
      print("Error in geospatial query: $error");
    });
  }

**Comment by kosukesaigusa** [comment]
Could share the screenshot of the document stored in Firestore?

**Comment by sabahsayedk2000** [comment]
![Uploading Screenshot 2024-11-19 at 5.46.14 PM.png…]()

**Comment by sabahsayedk2000** [comment]
<img width="911" alt="Screenshot 2024-11-19 at 5 46 36 PM" src="https://github.com/user-attachments/assets/c72ba28a-1f7b-4a8e-9775-6e5b5acc683f">

**Comment by sabahsayedk2000** [comment]
<img width="601" alt="Screenshot 2024-11-19 at 11 59 02 AM" src="https://github.com/user-attachments/assets/3c22fa6a-85f7-4905-9255-58be71fb1b91">

**Comment by sabahsayedk2000** [comment]
<img width="601" alt="Screenshot 2024-11-19 at 11 59 02 AM" src="https://github.com/user-attachments/assets/c4c7c643-0513-4926-9f4c-08c9b04ef6e2">

**Comment by kosukesaigusa** [comment]
@sabahsayedk2000 

Your screenshot seems the document is missing geohash field.

Refer to the similar screenshot in README, and save the document correctly!

<img width="785" alt="000926@2x" src="https://github.com/user-attachments/assets/f1a165c1-bddc-450c-a4ee-18dd2e949cdb">
